server:
  port : 5005

spring:
  data:
    mongodb:
      host: localhost
      post: 27017
      database: bankaccount
  kafka:
    producer:
      boottrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      propertis:
        spring:
          json:
            trusted:
              packages: '*'
